services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - config.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - "litellm"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"

  litellm:
    image: "ghcr.io/opendevin/sandbox:v0.1"
    ports:
      - "5000:5000"
